apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

# "app.kubernetes.io/component" label is set per resource to ensure network routing separation between workloads.
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/created-by: harmelodic
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: init-microservice
      app.kubernetes.io/part-of: init-microservice
      app.kubernetes.io/version: 1.0.0
