apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-microservice
  template:
    metadata:
      labels:
        app: init-microservice
    spec:
      serviceAccountName: init-microservice
      containers:
        - name: init-microservice
          image: init-microservice:v1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: management-http
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 0.25Gi
          startupProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /actuator/health/liveness
              port: management-http
          readinessProbe:
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /actuator/health/readiness
              port: management-http
          livenessProbe:
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /actuator/health/liveness
              port: management-http
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
