management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    port: 8081
  tracing:
    enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
spring:
  application:
    name: init-microservice
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/init-microservice
    username: init-microservice
    # Configure DB driver or use Cloud-provider specific datasource settings.

# Custom App properties
app:
  customer:
    client:
      baseUrl: http://customer-api
