# For running locally, using runtime mocks and in-memory databases.
logging:
  config: classpath:/logback-dev-local.xml
management:
  tracing:
    enabled: false
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:init-microservice
    username: init-microservice
