apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-microservice
  labels:
    app.kubernetes.io/component: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: deployment
    spec:
      serviceAccountName: init-microservice
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: init-microservice
          image: init-microservice:v1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: http-management
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 0.25Gi
            limits:
              memory: 0.25Gi
          startupProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /actuator/health/liveness
              port: http-management
          readinessProbe:
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /actuator/health/readiness
              port: http-management
          livenessProbe:
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /actuator/health/liveness
              port: http-management
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
