apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: init-microservice
  template:
    metadata:
      labels:
        app: init-microservice
    spec:
      serviceAccountName: init-microservice
      containers:
        - name: init-microservice
          image: init-microservice:v1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "1"
              memory: 0.5Gi
            limits:
              cpu: "2"
              memory: 1Gi
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 60
            httpGet:
              port: 80
              path: /actuator/health
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 60
            httpGet:
              port: 80
              path: /actuator/health
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
