apiVersion: v1
kind: Service
metadata:
  name: init-microservice
  labels:
    app: init-microservice
spec:
  type: NodePort
  selector:
    app: init-microservice
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http