name: main
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 18
      - run: >-
          mvn deploy
          -Dmaven.deploy.skip=true
          -Dpact.broker.url=https://harmelodic.pactflow.io
          -Dpactbroker.url=https://harmelodic.pactflow.io
