name: main
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - run: |-
          mvn deploy \
          -Dimage.repository=init-microservice \
          -Dimage.tag=$GITHUB_SHA \
          -Dpactbroker.url=https://harmelodic.pactflow.io \
          -Dpact.verifier.publishResults=true \
          -Dpact.broker.url=https://harmelodic.pactflow.io \
          -Dpact.broker.token=$PACT_BROKER_TOKEN \
          -Dpact.broker.authentication.scheme=BEARER
