name: pull-requests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 18
      - run: mvn install
